<div class="payment-methods">

    

    <?php if(config('paypal-username', '') != ''):?>
        <div class="each">
            <a href="<?php echo url('payment/paypal', array('type' => $type, 'typeid' => $typeId, 'price' => $price))?>"><img style="width: 197px;position:relative;left: -3px;" src="<?php echo assetUrl('assets/images/paypal-btn.png')?>"/> </a>
        </div>
    <?php endif?>
    
    <div class="each">
        <a href="<?php echo url('payment/ebilling', array('type' => $type, 'typeid' => $typeId, 'price' => $price))?>"><img style="width: 197px;position:relative;left: -3px;" src="<?php echo assetUrl('assets/images/airtel-moov-payer.png')?>"/> </a>
    </div>

    <form action="https://mypvit.com/pvit-secure-full-api.kk" method="POST" id="payeForm" >
        <input type="hidden" name="tel_marchand" value="<?php echo config('am_marchand', '')?>">
        <input type="hidden" name="montant" value="<?php echo $price?>">
        <input type="hidden" name="ref" value="<?= $reference ?>">
        <input type="hidden" name="service" value="WEB">
        <input type="hidden" name="operateur" value="AM">
        <input type="hidden" name="redirect" value="<?php echo url('payment/pvit/complete', array('reference' => $reference,'type' => $type, 'typeid' => $typeId, 'price' => $price))?>">
        <div class="each">
            <button name="submitButton" value="PAYER" type="submit" class="btn btn-block btn-lg  mt-2 round-sm" style="width:200px;background-color: #7451eb;margin: auto;font-weight: bold;color:#fff"><img style="width:20px" src="<?php echo assetUrl('assets/images/am.png')?>"/> <?php _l('airtel-money')?> </button>
        </div>
    </form>

    <form action="https://mypvit.com/pvit-secure-full-api.kk" method="POST" id="payeForm" >
        <input type="hidden" name="tel_marchand" value="<?php echo config('mc-marchand', '') ?>">
        <input type="hidden" name="montant" value="<?php echo $price?>">
        <input type="hidden" name="ref" value="<?= $reference ?>">
        <input type="hidden" name="service" value="WEB">
        <input type="hidden" name="operateur" value="MC">
        <input type="hidden" name="redirect" value="<?php echo url('payment/pvit/complete', array('reference' => $reference, 'type' => $type, 'typeid' => $typeId, 'price' => $price))?>">
        <div class="each">
            <button name="submitButton" value="PAYER" type="submit" class="btn btn-block btn-lg  mt-2 round-sm" style="width:200px;background-color: #7451eb;margin: auto;font-weight: bold;color:#fff"><img style="width:20px" src="<?php echo assetUrl('assets/images/mc.png')?>"/> <?php _l('mobicash')?> </button>
        </div>
    </form>
    
    <?php Hook::getInstance()->fire('payment.method', null, array($price,$type,$typeId,$detail))?>
</div>