<div class="inner-container">
    <form   action="<?php echo getFullUrl(true)?>" class="general-form mb-5" method="post">
        <div class="upload-types">
            <h4><?php _l('privacy-policy')?></h4>
            <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <p>Chez Mood, nous voulons vous offrir la meilleure expérience possible. Pour ce faire, nous traitons certaines de vos données personnelles pour comprendre vos habitudes d&#039;écoute et développer le meilleur service pour vous et pour tous nos clients. Toutefois, soyez assuré que la confidentialité et la sécurité de vos données personnelles sont une priorité des plus importantes pour nous.</p>
                    <p>Le but de ce centre de confidentialité est de vous fournir plus d'informations sur les droits et les contrôles dont vous disposez sur vos données personnelles, mais aussi d'expliquer certaines sections importantes de notre <a href="/be-fr/legal/privacy-policy/plain/">Politique de confidentialité</a>.</p>

                    <h2 class="h1" id="privacy-center-what">Quelles données personnelles Mood recueille sur moi ?</h2>
                    <p>Il est très important pour nous que vous sachiez quelles données personnelles nous recueillons sur vous, comment nous les recueillons et pourquoi cela est nécessaire.</p>
                    <p>Nous collectons vos données personnelles de la manière suivante :</p>
                    <ol>
                        <li><b>Données personnelles recueillies lorsque vous vous inscrivez au Service Mood</b> : lorsque vous vous inscrivez au Service Mood, nous collectons certaines données personnelles pour vous permettre d'utiliser le Service Mood. Il s'agit de la catégorie Données d'inscription du compte décrite dans la section 5 de notre Politique de confidentialité.</li>
                        <li><b>Données personnelles recueillies via votre utilisation du Service Mood</b> : lorsque vous utilisez le Service Mood, nous collectons des données personnelles relatives à votre utilisation de ce service, comme les titres que vous avez écoutés et les playlists que vous avez créées. Il s'agit de la catégorie Données d'utilisation du Service Mood figurant dans la section 5 de notre Politique de confidentialité.</li>
                        <li><b>Données personnelles collectées dans le but de vous fournir des fonctions/fonctionnalités supplémentaires</b> : vous pouvez parfois nous fournir des données personnelles complémentaires ou nous donner votre autorisation pour la collecte de données personnelles, par exemple pour profiter de fonctions ou fonctionnalités supplémentaires. Il s'agit des catégories Données mobiles volontaires, Données de paiement, Données relatives aux concours, sondages et tirages au sort, ainsi que Données marketing figurant dans la section 5 de notre Politique de confidentialité. Vous aurez toujours la possibilité de changer d'avis et de retirer votre autorisation à tout moment.</li>
                    </ol>

                    <h2 class="h1" id="privacy-center-why">Pourquoi Mood recueille et utilise ces données personnelles ?</h2>
                    <p>Nous collectons et utilisons vos données personnelles pour les raisons suivantes :</p>
                    <ul>
                        <li>Fournir, personnaliser et améliorer votre expérience du Service Mood et autres services et produits proposés par Mood.</li>
                        <li>Comprendre comment vous accédez au Service Mood et comment vous l&#039;utilisez pour garantir la fonctionnalité technique du Service, développer de nouveaux produits et services, et analyser votre utilisation du Service de Mood.</li>
                        <li>Communiquer avec vous pour des raisons liées au Service Mood.</li>
                        <li>Traiter vos paiements et prévenir ou détecter les fraudes, y compris les paiements frauduleux et l&#039;utilisation frauduleuse du Service Mood.</li>
                        <li>Communiquer avec vous, soit directement, soit via l&#039;un de nos partenaires, pour :
                            <ul>
                                <li>le marketing,</li>
                                <li>la recherche,</li>
                                <li>la participation à des concours, sondages et tirages au sort,</li>
                                <li>des fins promotionnelles,</li>
                            </ul>
                            par e-mails, notifications ou autres messages, conformément aux autorisations que vous nous avez données.</li>
                        <li>Vous fournir des fonctionnalités, des informations, de la publicité ou tout autre contenu basé sur votre emplacement spécifique.</li>
                        <li>D&#039;autres fins commerciales légitimes, comme expliqué dans la Politique de confidentialité.</li>
                    </ul>
                    <p>Pour en savoir plus sur les raisons pour lesquelles Mood utilise vos données personnelles, consultez notre Politique de confidentialité.</p>

                    <h2 class="h1" id="privacy-center-how">Comment Mood protège mes données personnelles ?</h2>
                    <p>Nous nous engageons à protéger les données personnelles de nos utilisateurs. Nous mettons en œuvre des mesures techniques et organisationnelles appropriées afin de protéger la sécurité de vos données personnelles. Cependant, veuillez noter qu&#039;aucun système n&#039;est totalement sûr. Nous avons mis en place diverses politiques, y compris des politiques de pseudonyme, de chiffrement, d&#039;accès et de conservation visant à empêcher tout accès non autorisé et toute conservation inutile des données personnelles dans nos systèmes.</p>
                    <p>Votre mot de passe protège votre compte utilisateur, nous vous encourageons donc à utiliser un mot de passe sûr et unique, à limiter l&#039;accès à votre ordinateur et votre navigateur et à vous déconnecter après avoir utilisé le Service Mood.</p>

                    <h2 class="h1">Comment Mood partage/transfert mes données personnelles ?</h2>
                    <p>Mood partage vos données personnelles avec d&#039;autres entreprises mondiales du groupe Mood.</p>
                    <p>Mood peut également sous-traiter le traitement ou partager vos données personnelles avec des tiers, situés dans un pays autre que votre pays d&#039;origine. Vos données personnelles peuvent donc être soumises à des lois sur la confidentialité différentes de celles de votre pays de résidence.</p>
                    <p>Les données personnelles recueillies dans l&#039;Union européenne (« UE ») et la Suisse peuvent, par exemple, être transférées et traitées par des tiers situés dans un pays en dehors de l&#039;UE et de la Suisse. Dans ce cas, Mood doit s&#039;assurer que le transfert de vos données personnelles est effectué conformément à la législation applicable et, en particulier, que des dispositions contractuelles, techniques et organisationnelles adaptées sont mises en place, comme les clauses contractuelles types approuvées par la commission de l&#039;UE.</p>
                    <h2 class="privacy-center-first-header h1">Vos droits sur vos données personnelles</h2>
                        <p>Comme vous le savez peut-être, un nouveau règlement de l&#039;Union européenne, appelé le Règlement général sur la protection des données ou « RGPD », accorde aux personnes certains droits relatifs à leurs données personnelles. En conséquence, nous avons mis en œuvre des contrôles d&#039;accès et des mesures de transparence supplémentaires dans notre centre de confidentialité et dans nos paramètres de confidentialité, afin d&#039;aider les utilisateurs à bénéficier de ces droits. Sauf limitations posées par la législation applicable, chaque personne dispose des droits décrits ci-dessous :</p>
                        <div class="privacy-center-rights-two-bundle">
                            <div class="col-lg-6 privacy-center-rights-left-col">
                                <h3>Accès à vos données personnelles</h3>
                                <p>Droit d&#039;être informé et de demander l&#039;accès aux données personnelles que nous traitons.</p>
                            </div>
                            <div class="col-lg-6 privacy-center-rights-right-col">
                                <h3>Mise à jour de vos données personnelles</h3>
                                <p>Droit de nous demander de modifier ou de mettre à jour vos données personnelles lorsqu&#039;elles sont inexactes ou incomplètes.</p>
                            </div>
                        </div>
                        <div class="privacy-center-rights-two-bundle">
                            <div class="col-lg-6 privacy-center-rights-left-col">
                                <h3>Restriction de l&#039;utilisation de vos données personnelles</h3>
                                <p>Droit de nous demander d&#039;arrêter temporairement ou définitivement le traitement de tout ou partie de vos données personnelles.</p>
                            </div>
                            <div class="col-lg-6 privacy-center-rights-right-col">
                                <h3>Refus de l&#039;utilisation de vos données personnelles</h3>
                                <p>Droit de refuser le traitement de vos données personnelles lorsque nous ne pouvons pas justifier la nécessité de ce traitement pour des raisons légitimes ou légales.</p>
                            </div>
                        </div>
                        <div class="privacy-center-rights-two-bundle">
                            <div class="col-lg-6 privacy-center-rights-left-col">
                                <h3>Refus du marketing direct</h3>
                                <p>Droit de refuser le traitement de vos données personnelles à des fins de marketing direct.</p>
                            </div>
                            <div class="col-lg-6 privacy-center-rights-right-col">
                                <h3>Refus de la prise de décision automatisée</h3>
                                <p>Droit de ne pas être soumis à une décision basée uniquement sur la prise de décision automatisée, y compris le profilage, dans le cas où la décision aurait un effet juridique sur vous ou produirait un effet significatif similaire.</p>
                            </div>
                        </div>
                        <div class="privacy-center-rights-two-bundle">
                            <div class="col-lg-6 privacy-center-rights-left-col">
                                <h3>Portabilité de vos données personnelles</h3>
                                <p>Droit de demander une copie de vos données personnelles dans un format lisible par une machine et droit de transmettre ces données personnelles pour une utilisation par un service tiers.</p>
                            </div>
                            <div class="col-lg-6 privacy-center-rights-right-col">
                                <h3>Suppression de vos données personnelles</h3>
                                <p>Droit de nous demander de supprimer définitivement vos données personnelles.</p>
                            </div>
                        </div>
                                                                            <p>Si vous avez d&#039;autres questions, reportez-vous à la section FAQ de ce Centre de confidentialité ou contactez-nous en utilisant le formulaire de contact</p>
                                            </div>
                                            <h2 id="privacy-center-control-section"
                        class="privacy-center-first-header h1">Où puis-je aller pour contrôler les données personnelles que Mood utilise ?</h2>
                                            <p>Vous pouvez accéder aux contrôles suivants via la page Paramètres du compte :</p>
                                        <ol>
                        <li><b>Page Paramètres de confidentialité</b> : elle vous permet de contrôler certaines catégories de données personnelles traitées, d'accéder à vos données personnelles via le bouton « Télécharger mes données » et comprend un lien vers le Centre de confidentialité sur Mood.com, où vous trouverez plus d'informations sur l'utilisation de vos données personnelles par Mood, ainsi que sur vos droits.</li>
                        <li><b>Page Paramètres de notification</b> : elle vous permet de choisir les communications que vous recevez de Mood, de gérer vos données personnelles accessibles au public et de définir vos préférences de partage.</li>
                    </ol>
                                            <p>Pour plus d&#039;informations sur les données personnelles que vous pouvez contrôler depuis la page Paramètres du compte, consultez vos droits en matière de données et vos paramètres de confidentialité.</p>
                                        <h2 class="h1"
                        id="privacy-center-policies">Nos politiques</h2>
                    <p>Chez Mood, nous nous engageons à vous offrir la meilleure expérience musicale possible. Les politiques que nous appliquons lorsque nous vous fournissons ce service sont décrites ci-dessous.</p>
                    <a href="/be-fr/legal/privacy-policy/plain/">
                        <div
                            class="panel panel-default privacy-center-policy-panel ">
                            <div class="panel-body">
                                <h4>Politique de confidentialité<span
                                        class="privacy-center-arrow">↗</span></h4>
                                <p>Notre Politique de confidentialité détaille les données personnelles que nous recueillons, comment nous les utilisons, et pourquoi nous les traitons.</p>
                            </div>
                        </div>
                    </a>
                    <a href="/be-fr/legal/cookies-policy/plain">
                        <div
                            class="panel panel-default privacy-center-policy-panel ">
                            <div class="panel-body">
                                <h4>Règlement sur les cookies<span
                                        class="privacy-center-arrow">↗</span></h4>
                                <p>Notre Règlement sur les cookies contient des informations sur les cookies utilisés par Mood, leur rôle pour nous aider à vous offrir la meilleure expérience possible et les choix dont vous disposez en matière de paramétrages de ces cookies.</p>
                            </div>
                        </div>
                    </a>
                    <h2 class="h1"
                        id="privacy-center-questions">Des questions ?</h2>
                    <p>Si vous avez des questions sur la confidentialité de vos données, notre Politique de confidentialité, les informations que nous détenons sur vous, ou vos droits et la façon de les exercer, <a href="mailto:privacy@Mood.com">contactez-nous</a>.</p>
                
            </div>
            <div class="col-md-2"></div>
        </div>
    </form>
</div>